crawler:
  movie:
    enabled: false
  episode:
    enabled: false
  mqtt:
    enabled: false
  headless:
    enabled: false


webdriver:
  remote:
    url: http://192.168.40.133:4444/wd/hub

spring:
  application:
    name: gm-crawling-service

mqtt:
  broker:
    protocol: tcp
    host: iot.eclipse.org
    port: 1883

